Update eyedetect.py
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("multiplyProbImages aborting - zero overlap. Offset and matrices:")?
 The above SyntaxError was corrected at line 345